In [6]:
import pandas as pd

df = pd.read_csv("../../data/primer-finder-fixed.csv", sep=";")

# family
forward_family_counts = df.groupby(['Order', 'Family', 'f_match']).size().reset_index(name='Count')
back_family_counts = df.groupby(['Order', 'Family', 'b_match']).size().reset_index(name='Count')
forward_family_counts.sort_values(by=['Order', 'Family', 'Count'], ascending=[True, True, False])
back_family_counts.sort_values(by=['Order', 'Family', 'Count'], ascending=[True, True, False])

# order
forward_order_counts = df.groupby(['Order', 'f_match']).size().reset_index(name='Count')
back_order_counts = df.groupby(['Order', 'b_match']).size().reset_index(name='Count')
forward_order_counts.sort_values(by=['Order', 'Count'], ascending=[True, False])
back_order_counts.sort_values(by=['Order', 'Count'], ascending=[True, False])

             Order                    b_match  Count
35              o:     CTGTTTTGGCTGGGGGTATTAC     15
12              o:    CCAGTTTTGGCCGGGGCCATTAC     14
0               o:    CCAGTACTAGCTGGTGCAATTAC     13
4               o:    CCAGTATTGGCTGGGGCTATTAC     11
8               o:    CCAGTTTTAGCTGGGGCTATTAC     10
...            ...                        ...    ...
50115  o:Zygentoma    CCTGTGTTAGCAGGAGCAATCAC      1
50116  o:Zygentoma    CCTGTTCTTGCAGGTGCTATTAC      1
50118  o:Zygentoma  CTGTTATAGGCGAGCGAGCTGACTT      1
50119  o:Zygentoma        TATTA-CCGCAG-TATTAC      1
50120  o:Zygentoma     TGCTCTCTA-CAAGAGAAATTA      1

[50122 rows x 3 columns]

In [7]:

# output
with pd.ExcelWriter('../../data/primer-counts-v2.xlsx', engine='openpyxl') as writer:
    forward_family_counts.sort_values(by=['Order', 'Family', 'Count'], ascending=[True, True, False]).to_excel(writer,
                                                                                                               sheet_name="forward_family",
                                                                                                               index=False)
    forward_order_counts.sort_values(by=['Order', 'Count'], ascending=[True, False]).to_excel(writer,
                                                                                              sheet_name="forward_order",
                                                                                              index=False)
    back_family_counts.sort_values(by=['Order', 'Family', 'Count'], ascending=[True, True, False]).to_excel(writer,
                                                                                                            sheet_name="back_family",
                                                                                                            index=False)
    back_order_counts.sort_values(by=['Order', 'Count'], ascending=[True, False]).to_excel(writer,
                                                                                           sheet_name="back_order",
                                                                                           index=False)