In [4]:
import pandas as pd

df = pd.read_csv("../../data/primer-finder-v2.csv", sep=";")

# family
forward_family_counts = df.groupby(['Order', 'Family', 'f_match']).size().reset_index(name='Count')
back_family_counts = df.groupby(['Order', 'Family', 'b_match']).size().reset_index(name='Count')
forward_family_counts.sort_values(by=['Order', 'Family', 'Count'], ascending=[True, True, False])
back_family_counts.sort_values(by=['Order', 'Family', 'Count'], ascending=[True, True, False])

# order
forward_order_counts = df.groupby(['Order', 'f_match']).size().reset_index(name='Count')
back_order_counts = df.groupby(['Order', 'b_match']).size().reset_index(name='Count')
forward_order_counts.sort_values(by=['Order', 'Count'], ascending=[True, False])
back_order_counts.sort_values(by=['Order', 'Count'], ascending=[True, False])

             Order                    b_match  Count
35              o:    CCTGTTTTGGCTGGGGGTATTAC     15
12              o:    CCAGTTTTGGCCGGGGCCATTAC     14
0               o:     CAGTACTAGCTGGTGCAATTAC     13
5               o:    CCAGTATTGGCTGGGGCTATTAC     11
8               o:    CCAGTTTTAGCTGGGGCTATTAC      9
...            ...                        ...    ...
45620  o:Zygentoma       CCTGTCCTGGCAGGAGCTAT      1
45622  o:Zygentoma    CCTGTGTTAGCAGGAGCAATCAC      1
45623  o:Zygentoma    CCTGTTCTTGCAGGTGCTATTAC      1
45625  o:Zygentoma  CTGTTATAGGCGAGCGAGCTGACTT      1
45626  o:Zygentoma    TGTTTTTGCGGGATCAATGTTAC      1

[45627 rows x 3 columns]

In [5]:

# output
with pd.ExcelWriter('../../data/primer-counts.xlsx', engine='openpyxl') as writer:
    forward_family_counts.sort_values(by=['Order', 'Family', 'Count'], ascending=[True, True, False]).to_excel(writer,
                                                                                                               sheet_name="forward_family",
                                                                                                               index=False)
    forward_order_counts.sort_values(by=['Order', 'Count'], ascending=[True, False]).to_excel(writer,
                                                                                              sheet_name="forward_order",
                                                                                              index=False)
    back_family_counts.sort_values(by=['Order', 'Family', 'Count'], ascending=[True, True, False]).to_excel(writer,
                                                                                                            sheet_name="back_family",
                                                                                                            index=False)
    back_order_counts.sort_values(by=['Order', 'Count'], ascending=[True, False]).to_excel(writer,
                                                                                           sheet_name="back_order",
                                                                                           index=False)